select
    date_entered as "Fecha de Creación",
    date_modified as "Última Modificación",
    description as "Descripción",
    deleted as "Eliminado",
    salutation as "Saludo",
    first_name as "Nombre",
    last_name as "Apellidos",
    title as "Cargo",
    department as "Departamento",
    do_not_call as "No llamar",
    phone_home as "Tel. casa",
    phone_mobile as "Móvil",
    phone_work as "Tel. oficina",
    phone_other as "Tel. alternativo",
    phone_fax as "Fax",
    (select email_address 
        from email_addr_bean_rel left join email_addresses on (email_addr_bean_rel.email_address_id=email_addresses.id)
        where email_addr_bean_rel.bean_id = leads.id
    ) as "Correo electrónico",
    primary_address_street as "Calle de dirección principal",
    primary_address_city as "Ciudad de dirección principal",
    primary_address_state as "Estado/Provincia de dirección principal",
    primary_address_postalcode as "CP de dirección principal",
    primary_address_country as "País de dirección principal",
    alt_address_street as "Calle de dirección alternativa",
    alt_address_city as "Ciudad de dirección alternativa",
    alt_address_state as "Estado/Provincia de dirección alternativa",
    alt_address_postalcode as "CP de dirección alternativa",
    alt_address_country as "País de dirección alternativa",
    assistant as "Asistente",
    assistant_phone as "Tel. Asistente",
    converted as "Convertido",
    refered_by as "Referido por",
    lead_source as "Toma de contacto",
    lead_source_description as "Descripción de toma de contacto",
    status as "Estado",
    status_description as "Descripción estado",
    account_name as "Nombre de cuenta",
    account_description as "Descripción de la Cuenta",
    opportunity_name as "Nombre de la oportunidad",
    opportunity_amount as "Cantidad de la oportunidad",
    birthdate as "Cumpleaños",
    website as "Sitio Web",
    crm_enviado_a_sci_c as "Enviado a SCI",
    crm_city_c as "Ciudad",
    crm_segundo_nombre_c as "Segundo nombre",
    sci_estado_credito_desc_c as "sci estado credito desc c",
    sci_subestado_credito_c as "sci subestado credito c",
    sci_cod_agenda_c as "Código Agenda SCI",
    crm_fullname_c as "Nombre y Apellido",
    crm_primer_nombre_c as "Primer nombre",
    sci_subestado_credito_char_c as "sci subestado credito char c",
    crm_variant_c as "crm variant c",
    sci_subestado_credito_desc_c as "Sub estado creditos",
    crm_apellido_materno_c as "Apellido materno",
    sci_estado_credito_c as "sci estado credito c",
    crm_apellido_paterno_c as "Apellido paterno",
    crm_landing_code_c as "crm landing code c",
    sfi_nro_prestamo_c as "Nro. préstamo",
    sfi_nro_cuenta_c as "Nro. cuenta",
    crm_amount_c as "Monto en Bs.",
    crm_datetime_c as "Fecha y hora",
    sci_estado_credito_char_c as "sci estado credito char c",
    cc_priorizar_c as "cc priorizar",
    cc_actividad_c as "cc actividad"

from 
    leads left join leads_cstm on (leads.id=leads_cstm.id_c)
where
    date_entered >= DATE_FORMAT(NOW() ,'%Y-01-01')
order by date_entered
